### PR TITLE
Feature/splash screen

### PR DESCRIPTION
**Pull request by mohamedelmeshtawy6**
added splash screen **successfully** ✔

for android & ios 
for android12+
433666919_931172801845406_8063115472957601217_n

### CODE REVIEW

**Review by mohamedabdelmonem425 — COMMENTED** [review]
very good but you change on boarding screen

**Review by mohamedelmeshtawy6 — COMMENTED** [review]
as it was found in dev branch

**Comment by mohamedabdelmonem425** [comment]
delete it please and make pr again

**Comment by mohamedelmeshtawy6** [comment]
oka

**Pull request closed without merging**
